trigger: none

pool: Pra_pipe

stages:
  - stage: MavenInstallation
    jobs:
      - job: MavenInstallation
        displayName: Maven Installation
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'Websure_Service_Connection1'
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
        
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              mvn clean package
              
              cp target/JavaLoginShowcase-1.0.0.war $TOMCAT_HOME/webapps/