trigger: none

pool: Pra_pipe

stages:
  - stage: MavenInstallation
    jobs:
      - job: MavenInstallation
        displayName: Maven Installation
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'Websure_Service_Connection1'
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false